{{- $namespaces := list .Values.namespace "draas-connectors" "draas-backup" "draas-audit" .Values.k8sZfs.recoveryNamespace "draas-observability" -}}
{{- range $namespaces | uniq }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    app.kubernetes.io/part-of: draas
    pod-security.kubernetes.io/enforce: baseline
---
{{- end }}
