const root=document.querySelector('#app');
const state={token:'',brand:'DR Platform',page:'overview',session:null,cursor:'',history:[],busy:false};
const pages=[['overview','Visão geral'],['environments','Ambientes'],['workloads','Workloads'],['recovery-points','Recovery points'],['recovery-jobs','Recovery real'],['activation-sessions','DR ativo'],['power-actions','Power actions'],['tests','Testes de DR'],['capacity','Capacidade'],['audit','Auditoria'],['infrastructure','Infraestrutura'],['jobs','Execuções']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>n==null?'—':`${(n/1048576).toFixed(1)} MiB`;
const date=s=>s?new Date(s).toLocaleString('pt-BR'):'—';
const short=s=>s?`${s.slice(0,13)}…${s.slice(-5)}`:'—';
const labels={VERIFIED:'Verificado',STORED:'Aguardando verificação',INVALID:'Inválido',COMPLETED:'Concluído',QUEUED:'Na fila',RUNNING:'Em execução',RETRYING:'Nova tentativa',CANCELLED:'Cancelado',FAILED:'Falhou',HEALTHY:'Disponível',UNAVAILABLE:'Indisponível',NOT_CONFIGURED:'Não configurado',SIMULATOR:'Simulador',DEPLOYMENT_MANAGED:'Gerenciado via Kubernetes',ACTIVE:'Ativo',TEST_PASSED:'Teste passou',READY_FOR_ACTIVATION:'Pronto para ativação'};
function badge(s){const good=['VERIFIED','COMPLETED','HEALTHY'].includes(s),bad=['INVALID','FAILED','UNAVAILABLE'].includes(s);return `<span class="badge ${good?'good':bad?'bad':'warn'}">${good?'✓':bad?'!':'○'} ${esc(labels[s]||s)}</span>`}
async function api(path,options={}){const response=await fetch(`/api/v1/${path}`,{...options,headers:{Authorization:`Bearer ${state.token}`,'Content-Type':'application/json',...(options.headers||{})}});const type=response.headers.get('Content-Type')||'';const data=type.includes('json')?await response.json():await response.text();if(!response.ok){throw new Error(data.message?`${data.message} [${data.correlation_id||data.error_code}]`:`Requisição falhou (${response.status})`)}return data}
function notify(message,error=false){const el=document.querySelector('#notice');if(el){el.className=`notice ${error?'error':'success'}`;el.textContent=message;el.hidden=false}}
function login(error=''){root.innerHTML=`<main class="login"><div class="eyebrow">RECUPERABILIDADE COMPROVADA</div><h1>${esc(state.brand)}</h1><p>Entre no laboratório para proteger dados, verificar integridade e testar a recuperação.</p><div class="notice">Ambiente de simulação. Nenhum teste deste laboratório comprova boot de uma VM.</div><form id="login"><label for="token">Credencial de acesso</label><input id="token" type="password" autocomplete="off" required minlength="32" placeholder="Token gerado pelo bootstrap"><button class="primary">Entrar no laboratório</button></form><p id="login-error" role="alert">${esc(error)}</p></main>`;document.querySelector('#login').addEventListener('submit',async e=>{e.preventDefault();state.token=document.querySelector('#token').value.trim();try{state.session=await api('session');await render()}catch(err){state.token='';login(err.message)}})}
function shell(){root.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand">${esc(state.brand)}<small>DISASTER RECOVERY</small></div><nav class="nav" aria-label="Navegação principal">${pages.map(([id,name])=>`<button data-page="${id}" class="${state.page===id?'active':''}" ${state.page===id?'aria-current="page"':''}>${name}</button>`).join('')}</nav><div class="foot">Control plane · Kubernetes<br>Data plane · S3 externo<br>Recovery · Simulador</div></aside><div class="main"><header class="topbar"><span>Partner lab <span class="muted">/</span> <strong>${esc(state.session.tenant)}</strong></span><div class="actions"><span class="mode">LAB · SIMULAÇÃO</span><button id="logout">Sair</button></div></header><main class="content"><div id="notice" role="status" aria-live="polite" hidden></div><div id="view" aria-busy="true"><p class="loading">Carregando ${esc(pages.find(p=>p[0]===state.page)?.[1])}…</p></div><footer>Os resultados representam execuções reais sobre dados sintéticos. Boot, HA e RTO de produção aguardam validação em hypervisor.</footer></main></div></div><dialog id="dialog"></dialog>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.cursor='';state.history=[];render()});document.querySelector('#logout').onclick=()=>{state.token='';state.session=null;login()}}
function head(title,subtitle,action=''){return `<div class="pagehead"><div><div class="eyebrow">RECOVERY OPERATIONS</div><h1>${title}</h1><p>${subtitle}</p></div><div class="actions"><button id="refresh">↻ Atualizar</button>${action}</div></div>`}
function metric(title,value,detail){return `<div class="metric"><div class="eyebrow">${title}</div><div class="value">${value}</div><small>${detail}</small></div>`}
function empty(title,detail){return `<div class="empty"><strong>${title}</strong>${detail}</div>`}
function table(headers,rows){return `<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function row(k,v){return `<div class="row"><span>${k}</span><strong>${v}</strong></div>`}
function modal(title,body,onSubmit){const d=document.querySelector('#dialog');d.innerHTML=`<form id="modal-form"><h2>${title}</h2>${body}<div id="modal-error" role="alert"></div><div class="actions"><button type="button" id="close-dialog">Fechar</button>${onSubmit?'<button class="primary" type="submit">Confirmar</button>':''}</div></form>`;d.querySelector('#close-dialog').onclick=()=>d.close();d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(!onSubmit)return;const b=d.querySelector('[type=submit]');b.disabled=true;try{await onSubmit(new FormData(e.target));d.close();await render()}catch(err){d.querySelector('#modal-error').textContent=err.message}finally{b.disabled=false}};d.showModal()}
function inspect(title,data){modal(title,`<pre>${esc(JSON.stringify(data,null,2))}</pre><button type="button" id="download">Baixar JSON</button>`);document.querySelector('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`draas-evidence-${Date.now()}.json`;a.click();URL.revokeObjectURL(url)}}
function addWorkload(){modal('Adicionar workload simulado',`<p class="muted">Cria uma origem determinística com arquivo e serviço sintéticos. Nenhuma conexão externa é necessária.</p><label for="name">Nome do workload</label><input id="name" name="name" value="Linux · Aplicação de laboratório" required maxlength="120"><label for="size">Tamanho lógico (MiB)</label><input id="size" name="size" type="number" min="1" max="256" value="16" required>`,async data=>api('workloads',{method:'POST',body:JSON.stringify({name:data.get('name'),size_mib:Number(data.get('size'))})}))}
async function job(path,button){if(button)button.disabled=true;try{const j=await api(path,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:'{}'});notify(`Execução ${short(j.id)} recebida. Acompanhando progresso…`);await watch(j.id)}catch(err){notify(err.message,true)}finally{if(button)button.disabled=false}}
async function realRecovery(point,button,keep=false){if(button)button.disabled=true;try{const res=await api('recovery-jobs',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({recovery_point_id:point,provider_type:'LIBVIRT_LAB',keep_resources:keep})});state.page='recovery-jobs';notify(`${keep?'KEEP RECOVERY ENV':'TEST RECOVERY'} recebido. Job ${short(res.job.id)} em execução.`);await watch(res.job.id)}catch(err){notify(err.message,true)}finally{if(button)button.disabled=false}}
async function activateDR(job,button){if(button)button.disabled=true;try{const res=await api(`recovery-jobs/${job}/activate`,{method:'POST',body:JSON.stringify({reason:'LAB_ACTIVATE_DR'})});state.page='activation-sessions';await render();notify(`DR ACTIVE · sessão ${short(res.activation_session.id)} · billing active=${res.billing_active}`)}catch(err){notify(err.message,true)}finally{if(button)button.disabled=false}}
async function powerVM(session,vm,action,button){if(button)button.disabled=true;try{const j=await api(`activation-sessions/${session}/vms/${vm}/${action}`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:'{}'});state.page='jobs';notify(`Power action ${action} recebida. Job ${short(j.id)} em execução.`);await watch(j.id)}catch(err){notify(err.message,true)}finally{if(button)button.disabled=false}}
async function watch(id){for(let i=0;i<90&&state.token;i++){const j=await api(`jobs/${id}`);if(['COMPLETED','FAILED','CANCELLED'].includes(j.status)){await render();notify(j.status==='COMPLETED'?`Execução concluída: ${j.kind}. Consulte a evidência em Execuções ou Testes de DR.`:`${labels[j.status]}: ${j.error||'Operação encerrada.'}`,j.status==='FAILED');return}notify(`${labels[j.status]||j.status} · ${bytes(j.progress_bytes)} processados · tentativa ${j.attempts}`);await new Promise(r=>setTimeout(r,2000))}notify('A execução continua no servidor. Acompanhe em Execuções.')}
async function render(){shell();const view=document.querySelector('#view');try{let html='';const page=state.page;
 if(page==='overview'){const [s,jobs]=await Promise.all([api('overview'),api('jobs?limit=5')]);const all=s.workloads>0&&s.rpo_compliant===s.workloads;html=head('Saúde da recuperação','Integridade, pontos utilizáveis e evidências em uma única visão.','<button id="add" class="primary">+ Proteger workload</button>')+`<section class="statushero ${all?'':'warning'}"><div class="symbol">${all?'✓':'○'}</div><div><div class="eyebrow">DR HEALTH · LABORATÓRIO</div><h2>${s.failed_jobs?'Execuções exigem atenção':all?'Dados verificados no simulador':'Proteção ainda não comprovada'}</h2><p>${all?'Os workloads têm recovery points verificados dentro do RPO.':'Crie um workload, execute um backup e aguarde a verificação de integridade.'} Boot e recuperabilidade em produção ainda não foram testados.</p></div></section><section class="metrics">${metric('Workloads',s.workloads,'Origens cadastradas')}${metric('Recovery points',s.verified_points,`${s.recovery_points} armazenados · integridade verificada`)}${metric('RPO no laboratório',s.workloads?`${Math.round(100*s.rpo_compliant/s.workloads)}%`:'—','Calculado somente com pontos válidos')}${metric('RTO validado','—','Requer teste de boot real')}</section><div class="split"><section class="panel"><div class="panelhead"><h2>Execuções recentes</h2></div>${jobs.items.length?table(['Operação','Estado','Processado'],jobs.items.map(j=>`<tr><td>${esc(j.kind)}<small>${date(j.created_at)}</small></td><td>${badge(j.status)}</td><td>${bytes(j.progress_bytes)}</td></tr>`)):empty('Nenhuma execução','Comece protegendo um workload simulado.')}</section><section class="panel"><h2>Critérios de recuperabilidade</h2>${row('Integridade criptográfica',`${s.verified_points} pontos verificados`)}${row('Boot de VM','Não testado')}${row('Capacidade de recovery','Não medida')}${row('Imutabilidade WORM','Não configurada')}${row('Armazenamento lógico',bytes(s.logical_bytes))}<div class="flow"><span>Capturar</span><span>Verificar</span><span>Restaurar</span><span>Validar</span></div></section></div>`}
 else if(page==='environments'){html=head('Ambientes','Descoberta e proteção das origens.')+`<div class="notice">O conector disponível é o simulador. Proxmox, VMware e agentes físicos aguardam integração e testes em laboratório real.</div><section class="panel"><h2>Laboratório local</h2>${row('Conector','Source Simulator')}${row('Snapshot','Determinístico por revisão')}${row('Incremental','Deduplicação; sem CBT')}${row('Consistência','Aplicação sintética')}<div class="actions"><button class="primary" id="add">Adicionar workload</button></div></section>`}
 else if(page==='capacity'){const s=await api('overview');html=head('Capacidade','Dimensionamento baseado em medições, sem promessas de RTO.')+`<section class="metrics">${metric('Dados lógicos',bytes(s.logical_bytes),'Soma dos recovery points')}${metric('Throughput de restore','—','Consulte cada relatório de teste')}${metric('Compute disponível','—','Provider real não conectado')}${metric('RTO estimado','—','Qualificação de hardware pendente')}</section><section class="panel"><h2>Qualificação necessária</h2><p>O throughput do simulador mede processamento de dados sintéticos e não dimensiona uma recuperação de VMs. Use os benchmarks do repositório para medir o pipeline; CPU, RAM, rede e storage do destino devem ser qualificados antes de contratar RTO.</p></section>`}
 else if(page==='infrastructure'){const s=await api('infrastructure');html=head('Infraestrutura','Estado consultado dos serviços que sustentam o laboratório.')+`<section class="panel">${Object.entries(s).map(([k,v])=>row(esc(k),badge(v))).join('')}</section>`}
 else {const data=await api(`${page}?limit=20&cursor=${encodeURIComponent(state.cursor)}`);const title=pages.find(p=>p[0]===page)[1];html=head(title,{workloads:'Gerencie revisões da origem e execute backups.', 'recovery-points':'Verifique, inspecione e restaure pontos do catálogo.', 'recovery-jobs':'TEST RECOVERY real via API, fila, worker e provider LIBVIRT_LAB. TEST permanece não faturável.', 'activation-sessions':'Sessões LIVE DR ativadas explicitamente. Billing só começa aqui.',tests:'Resultados medidos e relatórios assinados. Validação de simulador não comprova boot.',audit:'Registro de ações sensíveis, atores e correlação.',jobs:'Fila persistente, progresso em bytes e tentativas.'}[page],page==='workloads'?'<button id="add" class="primary">+ Adicionar workload</button>':'');html+='<section class="panel"><label class="sr-only" for="filter">Filtrar esta página</label><input class="filters" id="filter" placeholder="Filtrar esta página…">';
 if(!data.items.length){html+=empty('Nenhum registro encontrado',state.cursor?'Volte para a página anterior.':'Execute o fluxo de proteção para gerar dados e evidências.')}
 else if(page==='workloads'){html+=table(['Workload','Origem','Revisão / dados','RPO / RTO','Ações'],data.items.map(w=>`<tr><td><strong>${esc(w.name)}</strong><small class="mono">${esc(short(w.id))}</small></td><td>${w.active?'○ Simulador':'○ Origem removida'}</td><td>v${w.revision}<small>${bytes(w.size)}</small></td><td>${w.rpo_seconds}s / ${w.rto_seconds}s<small>Política do laboratório</small></td><td>${w.active?`<button data-job="workloads/${w.id}/backup">Backup</button><button data-mutate="${w.id}">Alterar dados</button><button class="danger" data-remove="${w.id}">Remover origem</button>`:'Recovery points preservados'}</td></tr>`))}
 else if(page==='recovery-points'){html+=table(['Recovery point','Integridade','Dados','Criado','Ações'],data.items.map(p=>`<tr><td class="mono">${esc(short(p.id))}<small>Workload ${esc(short(p.workload_id))}</small></td><td>${badge(p.status)}</td><td>${bytes(p.size)}<small>${p.stats.uploaded_chunks} novos · ${p.stats.reused_chunks} reutilizados</small></td><td>${date(p.created_at)}</td><td><button data-manifest="${p.id}">Inspecionar</button><button data-job="recovery-points/${p.id}/verify">Verificar</button>${p.status==='VERIFIED'?`<button data-real-recovery="${p.id}">TEST RECOVERY</button><button class="primary" data-keep-recovery="${p.id}">KEEP RECOVERY ENV</button><button data-job="recovery-points/${p.id}/test">Teste simulado</button>`:''}</td></tr>`))}
 else if(page==='recovery-jobs'){html+=table(['Recovery','Estado','Provider / billing','Report / ação'],data.items.map(r=>`<tr><td class="mono">${esc(short(r.id))}<small>Job ${esc(short(r.job_id))}</small><small>Point ${esc(short(r.recovery_point_id))}</small></td><td>${badge(r.status)}<small>${esc(r.stage)} · keep=${r.keep_resources}</small>${r.error?`<small>${esc(r.error)}</small>`:''}</td><td>${esc(r.provider_type)}<small>${r.billing_mode} · ${r.billable?'faturável':'não faturável'} · simulation=${r.simulation}</small></td><td>${r.report?`<button data-report='${esc(JSON.stringify(r.report))}'>Ver report</button>`:'Aguardando conclusão'}${r.status==='READY_FOR_ACTIVATION'?`<button class="danger" data-activate="${r.job_id}">ACTIVATE DR</button>`:''}</td></tr>`))}
 else if(page==='activation-sessions'){html+=table(['Sessão','Estado','Billing','Recursos'],data.items.map(s=>`<tr><td class="mono">${esc(short(s.id))}<small>Recovery ${esc(short(s.recovery_job_id))}</small></td><td>${badge(s.status)}<small>data_may_have_changed=${s.data_may_have_changed}</small></td><td>${s.billing_mode}<small>${s.billable?'Billing Active':'não faturável'} · ${esc(s.rate_plan_id)} v${s.rate_plan_version}</small></td><td><pre>${esc(JSON.stringify(s.provider_resource_ids))}</pre></td></tr>`))}
 else if(page==='power-actions'){html+=table(['Quando','Sessão / VM','Ação','Resultado'],data.items.map(a=>`<tr><td>${date(a.created_at)}</td><td class="mono">${esc(short(a.activation_session_id))}<small>VM ${esc(short(a.vm_id))}</small><small>Job ${esc(short(a.job_id))}</small></td><td>${esc(a.action)}<small>${esc(a.provider)}</small></td><td>${badge(a.status)}${a.error?`<small>${esc(a.error)}</small>`:''}<button data-report='${esc(JSON.stringify(a.provider_response))}'>Ver resposta</button></td></tr>`))}
 else if(page==='audit'){html+=table(['Quando','Ator','Operação','Correlação'],data.items.map(a=>`<tr><td>${date(a.created_at)}</td><td>${esc(a.actor)}</td><td>${esc(a.action)}</td><td class="mono">${esc(short(a.correlation_id))}</td></tr>`))}
 else {html+=table(['Operação','Estado','Processado','Evidência / ação'],data.items.map(j=>`<tr><td>${esc(j.kind)}<small>${date(j.created_at)}</small></td><td>${badge(j.status)}${j.error?`<small>${esc(j.error)}</small>`:''}</td><td>${bytes(j.progress_bytes)}<small>${j.attempts} tentativa(s)</small></td><td><button data-inspect="${j.id}">Detalhes e evidência</button>${['QUEUED','RUNNING','RETRYING'].includes(j.status)?`<button data-cancel="${j.id}">Cancelar</button>`:''}</td></tr>`))}
 html+=`<div id="no-results" class="empty" hidden>Nenhum resultado nesta página para o filtro.</div><div class="pagination">${state.history.length?'<button id="prev">← Anterior</button>':''}${data.next_cursor?'<button id="next">Próxima →</button>':''}</div></section>`;state.nextCursor=data.next_cursor}
 view.innerHTML=html;view.setAttribute('aria-busy','false');document.querySelector('#refresh').onclick=()=>render();document.querySelector('#add')?.addEventListener('click',addWorkload);
 document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>job(b.dataset.job,b));document.querySelectorAll('[data-real-recovery]').forEach(b=>b.onclick=()=>realRecovery(b.dataset.realRecovery,b,false));document.querySelectorAll('[data-keep-recovery]').forEach(b=>b.onclick=()=>realRecovery(b.dataset.keepRecovery,b,true));document.querySelectorAll('[data-activate]').forEach(b=>b.onclick=()=>activateDR(b.dataset.activate,b));document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>inspect('Evid?ncia JSON',JSON.parse(b.dataset.report)));document.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>powerVM(b.dataset.session,b.dataset.vm,b.dataset.power,b));document.querySelectorAll('[data-manifest]').forEach(b=>b.onclick=async()=>{try{inspect('Manifest assinado',await api(`recovery-points/${b.dataset.manifest}/manifest`))}catch(err){notify(err.message,true)}});document.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=async()=>{try{inspect('Execução e evidência',await api(`jobs/${b.dataset.inspect}`))}catch(err){notify(err.message,true)}});
 document.querySelectorAll('[data-mutate]').forEach(b=>b.onclick=async()=>{try{await api(`workloads/${b.dataset.mutate}/mutate`,{method:'POST',body:'{}'});await render();notify('Revisão alterada. Execute outro backup para medir reutilização de chunks.')}catch(err){notify(err.message,true)}});
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>modal('Remover origem simulada',`<p>Remove somente a disponibilidade da origem sintética. Os recovery points permanecem disponíveis para testar a recuperação sem a origem.</p>`,async()=>api(`workloads/${b.dataset.remove}/delete-source`,{method:'POST',body:JSON.stringify({confirm:b.dataset.remove})})));
 document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{try{await api(`jobs/${b.dataset.cancel}/cancel`,{method:'POST',body:'{}'});await render();notify('Cancelamento solicitado e registrado em auditoria.')}catch(err){notify(err.message,true)}});
 document.querySelector('#filter')?.addEventListener('input',e=>{let matches=0;document.querySelectorAll('tbody tr').forEach(tr=>{tr.hidden=!tr.textContent.toLowerCase().includes(e.target.value.toLowerCase());if(!tr.hidden)matches++});document.querySelector('#no-results').hidden=matches>0});
 document.querySelector('#next')?.addEventListener('click',()=>{state.history.push(state.cursor);state.cursor=state.nextCursor;render()});document.querySelector('#prev')?.addEventListener('click',()=>{state.cursor=state.history.pop()||'';render()});
 }catch(err){view.innerHTML=empty('Não foi possível carregar esta visão','Use Atualizar para tentar novamente.')+'<button id="retry">Atualizar</button>';view.setAttribute('aria-busy','false');document.querySelector('#retry').onclick=()=>render();notify(err.message,true)}}
try{const brand=await (await fetch('/api/v1/branding')).json();state.brand=brand.name;document.title=brand.name}catch{}login();
